### ISSUE TITLE
Wrapping private keys

### ISSUE THREAD

**Issue by btoews** [dimalinux/HsmKeyWrappingExample#1]
I was experimenting with key wrapping on a Luna a while back and it seems that they don't support wrapping RSA private keys (or any asymmetric private keys). Have you tried this at all? If so, did you have any luck?

**Comment by dimalinux** [comment]
I don't have access to a Luna HSM anymore.  What would be a use case for wrapping RSA private keys?  I can't think of an application that would need to store thousands of RSA private keys encrypted in a database.  (Or something similar.)  If you are hosting thousands of HTTPS domains on the same server, it might not be unreasonable to have them share the same private key.

**Comment by btoews** [comment]
We (GitHub) had been considering signing web-commits (Eg. merge button) with a per-user GPG key. That's 10M+ keys...

**Comment by dimalinux** [comment]
Wouldn't that mean that users would have to give Github their private GPG key?  The commits would be signed, but would the signatures have any true value if the private keys are not strictly under the user's control?

**Comment by btoews** [comment]
The key would be generated by us. The key would have an identity like `Ben Toews (@mastahyeti on GitHub.com) <whatever@whatever.com>` and would be signed by a GitHub, Inc key. If the person verifying the signature trusted GitHub, they would trust that @mastahyeti made the commit via GitHub's web interface.

**Comment by dimalinux** [comment]
If the verifying party trusted Github's key, would they need the separate @mastahyeti key?  Github's signing key could be generated inside an HSM and not be extractable.  An attacker could convince the HSM to sign something if it got access to the HSM, but they wouldn't be able to get the private key.  I could see the 2nd key being useful if the HSM that stores Github's signing key has a much higher level of security than the other HSMs that sign code commits.

In your scenario, the user's private key would need to be wrapped by a symmetric key (KEK) only known to the HSM for outside-HSM storage.   The KEK would need to be configured so that it can only unwrap the user's GPG private keys onto the HSM and only give out a reference to that unwrapped key (i.e. not the raw key).  If you do this wrong and the KEK is capable of doing general encryption/decryption (not just unwrapping), an attacker getting access to your encrypted keys and the HSM could decrypt everyone's private GPG keys.  Albeit, if they get access to your HSM and the user's encrypted key, the could still sign code even if the KEK is configured correctly.

You'll probably have to talk to one of Luna's engineers if your JCA code isn't working.  You might want to tinker with wrapping/unwrapping RSA keys generated outside the HSM just to see what's possible and working or not-working.

**Comment by btoews** [comment]
Yeah, from what I've found the Lunas are only able to wrap symmetric keys. I was just wondering if you'd found that to be the case. What we're more likely to do for web commits is to sign them all with a single GitHub key/identity.
